version: 2

sources: 
  - name: staging
    database: ny-taxi-terraform-416223
     # For postgres:
      #database: production
    schema: ny_taxi

      # loaded_at_field: record_loaded_at
    tables:
      - name: green_cab_data
      - name: yellow_cab_data

